### ISSUE TITLE
ZAP HUD Tutorial : Resend task needs rephrasing

### ISSUE THREAD

**Issue by Bal2018** [zaproxy/zap-hud#861] opened 2021-01-07 16:27 UTC
**Steps to reproduce:** 
Following the wording of the task in this module.

1. Select the GET request for this page in the History tab, 
2. Change the User-Agent to include ZAP 
3.  Click 'Replay in Browser'`

**Actual result:**
The user is taken back to the beginning of the HUD Tutorial.

**Expected result:**
The task should be highlighted as competed and the user should be able to proceed to the next step in this tutorial.

**Solution :**
The only way the user can complete the task is either by :- 
1. Turning the HUD off and manually moving to the next section
2. Deleting all the entry for User-Agent and adding just ZAP.  For this the user needs to know that they should  :-
`Select the GET request for this page in the History tab, change the User-Agent to have the value of ZAP and then 'Replay in Browser' `.

**Comment by kingthorin** [comment] 2021-01-07 16:42
Thanks, we'll re-test this and see if we can re-create the issue.

Could you let us know what browser and version you were using? Also did you launch the browser from within ZAP or did you manually set the proxy?

**Comment by computerist** [comment] 2021-01-07 16:50
> Thanks, we'll re-test this and see if we can re-create the issue.

I've also seen this; the issue is with the tutorial copy, not the actual code (as @Bal2018 notes in solution 2).

**Comment by kingthorin** [comment] 2021-01-07 17:27
I was referring to "The user is taken back to the beginning of the HUD Tutorial."

**Comment by computerist** [comment] 2021-01-08 10:48
Hmm, I don't see that either.

@Bal2018 do you mean that you're sent back to the first page of the "resend" task?

**Comment by thc202** [comment] 2021-01-11 11:22
Closing this per changes done in #862.

**Closed by thc202** 2021-01-11 11:22 UTC
Labels: enhancement

**Comment by Jason3-14Butler** [comment] 2022-03-29 15:39
I am not able to progress past the Resend stage of the HUD tutorial. I change the User-Agent to ZAP, however the Next: Spider button remains greyed out and disabled.
![ZAP_Resend_Hud - Copy](https://user-images.githubusercontent.com/26047046/160650510-573a488f-c90b-4e91-af43-8301c9469294.JPG)

**Comment by psiinon** [comment] 2022-04-04 16:54
@Jason3-14Butler asking for help via an issue that was closed over a year ago is not a good approach :)
You would be better off asking on the ZAP User Group: https://groups.google.com/group/zaproxy-users

**Comment by L0RDPeace** [comment] 2024-04-13 14:08
> I am not able to progress past the Resend stage of the HUD tutorial. I change the User-Agent to ZAP, however the Next: Spider button remains greyed out and disabled. ![ZAP_Resend_Hud - Copy](https://user-images.githubusercontent.com/26047046/160650510-573a488f-c90b-4e91-af43-8301c9469294.JPG)
> 
> I'm using OWASP ZAP Version 2.11.1 in Kali with Firefox launched from ZAP

Same thing with me
